### ISSUE TITLE
The type arguments for method 'Gradient.Interop.PythonifyDict<TKey,TValue> cannot be inferred

### ISSUE THREAD

**Issue by vera-dania** [losttech/Gradient#22]
Using the function ``` run_dyn ```  an RuntimeException was thrown 

Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: The type arguments for method 'Gradient.Interop.PythonifyDict<TKey,TValue>(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<TKey,TValue>>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Gradient.Interop.PythonifyEnumerable(IEnumerable enumerable)
   at Gradient.Interop.Pythonify(Object obj)
   at tensorflow.python.client.session.BaseSession.run_dyn(Object fetches, Object feed_dict, Object options, Object run_metadata).

**Comment by lostmsu** [comment]
@vera-dania can you tell what is the type of the dictionary you are passing (I am assuming to `feed_dict`)?

**Comment by vera-dania** [comment]
@lostmsu Yes, ```feed_dict``` I'm creating ```var placeholder_values = new PythonDict<object,  object>``` 
And the type of each object is ```<Tensor, ndarray[]>

**Comment by lostmsu** [comment]
Try using regular `Dictionary<object, object>`

**Comment by vera-dania** [comment]
@lostmsu That works. Thank you!

**Comment by lostmsu** [comment]
Fix released in Preview 7
